Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/LineLength:
  Max: 120
Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb
Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update